function calculateAndSaveGradientEdgeMaps(thresholds,outputFolderPath,image3063LStar,image8068LStar)
    createEdgeOutputFolders(outputFolderPath);
    %Image 3063
    % for iThreshold = 1:length(thresholds)
    %     [gradientEdgeMapSobel_0, gradientMagnitudeSobel_0] = ...
    %         detectEdges(image3063LStar, "Sobel",thresholds(iThreshold),0,0,0);
    %     [gradientEdgeMapPDDO_0, gradientMagnitudePDDO_0] = ...
    %         detectEdges(image3063LStar, "PDDOKernel",thresholds(iThreshold),2,0,7);
    %     [gradientEdgeMapPrewitt_0, gradientMagnitudePrewitt_0] = ...
    %         detectEdges(image3063LStar, "Prewitt",thresholds(iThreshold),0,0); 
    %     [gradientEdgeMapScharr_0, gradientMagnitudeScharr_0] = ...
    %         detectEdges(image3063LStar, "Scharr",thresholds(iThreshold),0,0,0);
    %     [gradientEdgeMapMacleod_0, gradientMagnitudeMacleod_0] = ...
    %         detectEdges(image3063LStar, "Macleod",thresholds(iThreshold),2,2,7);
    %     [gradientEdgeMapArgyle_0, gradientMagnitudeArgyle_0] = ...
    %         detectEdges(image3063LStar, "Argyle",thresholds(iThreshold),2,0,7);
    %     imwrite(gradientEdgeMapSobel_0,...
    %         strcat(outputFolderPath,"3063/Sobel/Threshold_",...
    %         num2str(thresholds(iThreshold)),".png"))
    %     imwrite(gradientEdgeMapPDDO_0,...
    %         strcat(outputFolderPath,"3063/PDDO/Threshold_",...
    %         num2str(thresholds(iThreshold)),".png"))
    %     imwrite(gradientEdgeMapPrewitt_0,...
    %         strcat(outputFolderPath,"3063/Prewitt/Threshold_",...
    %         num2str(thresholds(iThreshold)),".png"))
    %     imwrite(gradientEdgeMapScharr_0,...
    %         strcat(outputFolderPath,"3063/Scharr/Threshold_",...
    %         num2str(thresholds(iThreshold)),".png"))
    %     imwrite(gradientEdgeMapMacleod_0,...
    %         strcat(outputFolderPath,"3063/Macleod/Threshold_",...
    %         num2str(thresholds(iThreshold)),".png"))
    %     imwrite(gradientEdgeMapArgyle_0,...
    %         strcat(outputFolderPath,"3063/Argyle/Threshold_",...
    %         num2str(thresholds(iThreshold)),".png"))
    % end
    
    %Image 3063 Fuzzy PDDO
    [modifiedMembershipImage, gradientMagnitude] = fuzzyPDDOEdgeDetector(image3063LStar, 2,11);
    for iThreshold = 1:length(thresholds)
        [gradientEdgeMapFuzzyPDDO_0, gradientMagnitudeFuzzyPDDO_0] = ...
            detectEdges(modifiedMembershipImage, "FuzzyPDDO",thresholds(iThreshold),0,0,0);
        imwrite(gradientEdgeMapFuzzyPDDO_0,...
            strcat(outputFolderPath,"3063/FuzzyPDDO/Threshold_",...
            num2str(thresholds(iThreshold)),".png"));
    end
    %Image 3063 Fuzzy PDDO
    [modifiedMembershipImage, gradientMagnitude] = fuzzyType2PDDOEdgeDetector(image3063LStar, 2,11);
    for iThreshold = 1:length(thresholds)
        [gradientEdgeMapFuzzyType2PDDO_0, gradientMagnitudeFuzzyType2PDDO_0] = ...
            detectEdges(modifiedMembershipImage, "FuzzyType2PDDO",thresholds(iThreshold),0,0,0);
        imwrite(gradientEdgeMapFuzzyType2PDDO_0,...
            strcat(outputFolderPath,"3063/FuzzyType2PDDO/Threshold_",...
            num2str(thresholds(iThreshold)),".png"));
    end

    %Image 8068
    % for iThreshold = 1:length(thresholds)
    %     [gradientEdgeMapSobel_0, gradientMagnitudeSobel_0] = ...
    %         detectEdges(image8068LStar, "Sobel",thresholds(iThreshold),0,0,0);
    %     [gradientEdgeMapPDDO_0, gradientMagnitudePDDO_0] = ...
    %         detectEdges(image8068LStar, "PDDOKernel",thresholds(iThreshold),2,0,7);
    %     [gradientEdgeMapPrewitt_0, gradientMagnitudePrewitt_0] = ...
    %         detectEdges(image8068LStar, "Prewitt",thresholds(iThreshold),0,0); 
    %     [gradientEdgeMapScharr_0, gradientMagnitudeScharr_0] = ...
    %         detectEdges(image8068LStar, "Scharr",thresholds(iThreshold),0,0,0);
    %     [gradientEdgeMapMacleod_0, gradientMagnitudeMacleod_0] = ...
    %         detectEdges(image8068LStar, "Macleod",thresholds(iThreshold),2,2,7);
    %     [gradientEdgeMapArgyle_0, gradientMagnitudeArgyle_0] = ...
    %         detectEdges(image8068LStar, "Argyle",thresholds(iThreshold),2,0,7);
    % 
    %     imwrite(gradientEdgeMapSobel_0,...
    %         strcat(outputFolderPath,"8068/Sobel/Threshold_",...
    %         num2str(thresholds(iThreshold)),".png"))
    %     imwrite(gradientEdgeMapPDDO_0,...
    %         strcat(outputFolderPath,"8068/PDDO/Threshold_",...
    %         num2str(thresholds(iThreshold)),".png"))
    %     imwrite(gradientEdgeMapPrewitt_0,...
    %         strcat(outputFolderPath,"8068/Prewitt/Threshold_",...
    %         num2str(thresholds(iThreshold)),".png"))
    %     imwrite(gradientEdgeMapScharr_0,...
    %         strcat(outputFolderPath,"8068/Scharr/Threshold_",...
    %         num2str(thresholds(iThreshold)),".png"))
    %     imwrite(gradientEdgeMapMacleod_0,...
    %         strcat(outputFolderPath,"8068/Macleod/Threshold_",...
    %         num2str(thresholds(iThreshold)),".png"))
    %     imwrite(gradientEdgeMapArgyle_0,...
    %         strcat(outputFolderPath,"8068/Argyle/Threshold_",...
    %         num2str(thresholds(iThreshold)),".png"))
    % end

    %Image 8068 Fuzzy PDDO
    [modifiedMembershipImage, gradientMagnitude] = fuzzyPDDOEdgeDetector(image8068LStar, 2,11);
    for iThreshold = 1:length(thresholds)
        [gradientEdgeMapFuzzyPDDO_0, gradientMagnitudeFuzzyPDDO_0] = ...
            detectEdges(gradientMagnitude, "FuzzyPDDO",thresholds(iThreshold),0,0,0);
        imwrite(gradientEdgeMapFuzzyPDDO_0,...
            strcat(outputFolderPath,"8068/FuzzyPDDO/Threshold_",...
            num2str(thresholds(iThreshold)),".png"));
    end

    %Image 8068 Fuzzy Type 2 PDDO
    [modifiedMembershipImage, gradientMagnitude] = fuzzyType2PDDOEdgeDetector(image8068LStar, 2,11);
    for iThreshold = 1:length(thresholds)
        [gradientEdgeMapFuzzyType2PDDO_0, gradientMagnitudeFuzzyType2PDDO_0] = ...
            detectEdges(gradientMagnitude, "FuzzyType2PDDO",thresholds(iThreshold),0,0,0);
        imwrite(gradientEdgeMapFuzzyType2PDDO_0,...
            strcat(outputFolderPath,"8068/FuzzyType2PDDO/Threshold_",...
            num2str(thresholds(iThreshold)),".png"));
    end

end